### DISCUSSION TITLE
Why did the `nats-server` Rust crate get removed from crates-io?

### DISCUSSION THREAD

**Discussion by akbergsn** [nats-io/nats.rs#1394] [Q&A]
In this [question](https://github.com/nats-io/nats.rs/discussions/752), there is an answer that states a `nats-server` crate available, but I cannot find it. I assume at one point it was available?

**Comment by barafael** [comment]
it's a test-only crate, it spawns the **actual** nats server as a process. It isn't available on crates.io (and never was!). Instead, get it into your 

```toml
[dev-dependencies]
nats-server = { git = "https://github.com/nats-io/nats.rs" }
```
