### ISSUE TITLE
Consumer Stalls on high throughput

### ISSUE THREAD

**Issue by TroyKomodo** [nats-io/nats.rs#1285]
### Observed behavior

When consuming high volumes of requests/s consumers freeze and stop receiving events.

### Expected behavior

Things work flawlessly 

### Server and client version

nats-server: `nats:latest docker` running `2.10.17`
nats-client: `v0.1.1`
async-nats: `0.35.1`

### Host environment

Docker container

Single deployment using docker-compose
```yaml
services:
  nats:
    image: nats:latest
    pull_policy: "always"
    restart: unless-stopped
    ports:
      - "${NATS_BIND:-127.0.0.1:4222}:4222"
    command: -js -sd /data 
    volumes:
      - nats:/data
    deploy:
      resources:
        limits:
          memory: ${NATS_MEMORY:-4G}
volumes:
  nats:
```

### Steps to reproduce

```rs
use std::sync::{atomic::AtomicUsize, Arc};

use async_nats::jetstream::{self, stream::RetentionPolicy};
use futures::StreamExt;

#[tokio::main]
async fn main() {
    let nats = async_nats::connect("nats://127.0.0.1:4222").await.unwrap();
    let jetstream = async_nats::jetstream::new(nats);
    let stream = jetstream.get_or_create_stream(jetstream::stream::Config {
        name: "test".to_string(),
        retention: RetentionPolicy::WorkQueue,
        subjects: vec!["test".to_string()],
        ..Default::default()
    }).await.unwrap();
    let consumer = stream.create_consumer(jetstream::consumer::pull::Config {
        name: Some("test".to_string()),
        durable_name: Some("test".to_string()),
        ack_policy: jetstream::consumer::AckPolicy::Explicit,
        max_ack_pending: 1_000_000,
        ..Default::default()
    }).await.unwrap();

    const PERMITS: usize = 50_000;

    let message_count = Arc::new(AtomicUsize::new(0));
    let semaphore = Arc::new(tokio::sync::Semaphore::new(PERMITS));
    let mut messages = consumer.messages().await.unwrap();

    {
        let semaphore = semaphore.clone();
        let message_count = message_count.clone();
        tokio::spawn(async move {
            while let Some(msg) = messages.next().await.transpose().unwrap() {
                let ticket = semaphore.clone().acquire_owned().await.unwrap();
                message_count.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                tokio::spawn(async move {
                    tokio::time::sleep(std::time::Duration::from_secs(1)).await;
                    msg.ack().await.unwrap();
                    drop(ticket);
                });
            }
        });
    }

    loop {
        tokio::time::sleep(std::time::Duration::from_secs(1)).await;
        let mc = message_count.swap(0, std::sync::atomic::Ordering::Relaxed);
        println!("Received {}/s messages, inflight {}", mc, PERMITS - semaphore.available_permits());
    }
}
```

```bash
nats pub test --count=100000000 "{{Count}} @ {{Time}}"
```

https://github.com/user-attachments/assets/c6e9274e-67a3-4c41-b2d3-b88b6db2aeb5
